@{
    BoxScore          = "http://data.nba.com/data/5s/json/cms/noseason/game/{date}/{gameId}/boxscore.json"
    Calendar          = "http://data.nba.net/data/10s/prod/v1/calendar.json"
    Coaches           = "http://data.nba.com/data/10s/prod/v1/{season}/coaches.json"
    LeadTracker       = "http://data.nba.com/data/10s/prod/v1/{date}/{gameId}_lead_tracker_{period}.json"
    PlayByPlay        = "http://data.nba.com/data/5s/json/cms/noseason/game/{date}/{gameId}/pbp_all.json"
    PlayoffBracket    = "http://data.nba.com/data/10s/prod/v1/{season}/playoffsBracket.json"
    PlayerProfile     = "http://data.nba.net/data/10s/prod/v1/{year}/players/{playerId}_profile.json"
    Players           = "http://data.nba.net/data/10s/prod/v1/{year}/players.json"
    PreviewArticle    = "http://data.nba.com/data/10s/prod/v1/{date}/{gameId}_preview_article.json"
    RecapArticle      = "http://data.nba.com/data/10s/prod/v1/{date}/{gameId}_recap_article.json"
    Schedule          = "http://data.nba.com/data/10s/prod/v1/{season}/schedule.json"
    Scoreboard        = "http://data.nba.com/data/5s/json/cms/noseason/scoreboard/{date}/games.json"
    Standings         = "http://data.nba.net/data/10s/prod/v1/current/standings_{type}.json"
    TeamLeaders       = "http://data.nba.com/data/10s/prod/v1/{season}/teams/{teamId}/leaders.json"
    Teams             = "http://data.nba.net/data/10s/prod/v1/{year}/teams.json"
    TeamSchedule      = "http://data.nba.com/data/10s/prod/v1/{season}/teams/{teamId}/schedule.json"
    TeamStatsRankings = "http://data.nba.com/data/10s/prod/v1/{season}/team_stats_rankings.json"
    TeamRoster        = "http://data.nba.net/data/10s/prod/v1/{season}/teams/{teamName}/roster.json"
}
