#
# Module manifest for module 'PSNba'
#
# Generated by: alexm
#
# Generated on: 11/1/2020
#

@{

    # Script module or binary module file associated with this manifest.
    RootModule        = 'PSNba.psm1'

    # Version number of this module.
    ModuleVersion     = '1.0.1'

    # Supported PSEditions
    # CompatiblePSEditions = @()
    #test

    # ID used to uniquely identify this module
    GUID              = '41d13250-e060-41d8-90b2-e54cc40dc96b'

    # Author of this module
    Author            = 'Alex Milner'

    # Copyright statement for this module
    Copyright         = '(c) Alex Milner. All rights reserved.'

    # Description of the functionality provided by this module
    Description       = 'PowerShell module that uses the NBAs undocumented REST API to request data.'

    # Minimum version of the PowerShell engine required by this module
    # PowerShellVersion = ''

    # Type files (.ps1xml) to be loaded when importing this module
    # TypesToProcess = @()

    # Format files (.ps1xml) to be loaded when importing this module
    # FormatsToProcess = @()

    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    FunctionsToExport = @('*')

    # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
    CmdletsToExport   = @('*')

    # Variables to export from this module
    VariablesToExport = '*'

    # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
    AliasesToExport   = @()

    # HelpInfo URI of this module
    # HelpInfoURI = ''

}

